### ISSUE TITLE
500 Server Error: Internal Server Error ("invalid reference format: repository name must be lowercase")

### ISSUE THREAD

**Issue by JochenKlenk** [BiasF/Homegear4Homeassistant#1]
Hi,

I get 

500 Server Error: Internal Server Error ("invalid reference format: repository name must be lowercase")

when I try to install it in Homeassistant.

Can you help.

**Comment by BiasF** [comment]
Hi,

can you try again?

**Comment by JochenKlenk** [comment]
Perfect.It works.ThanksAm 04.11.2020 15:39 schrieb BiasF <notifications@github.com>:
Hi,
can you try again?

**Comment by BiasF** [comment]
fine 👍  :)

**Comment by maxbec** [comment]
Hey guys,

i still get the same error. Just tried it 2mins ago.

**Comment by BiasF** [comment]
Hi,

did you added the repo without capital letters?

Add it like this:
https://github.com/biasf/homegear4homeassistant/

**Comment by maxbec** [comment]
Ok it works. But homeassistant gets no information about the found devices. What is you configuration.yaml entry?

**Comment by BiasF** [comment]
Hi,

I answered in Homegear board.
As described in readme, the Config is:

```
homematic:
  interfaces:
    wireless:
      host: HASSIO-IP
      resolvenames: metadata
      port: 2001
```

**Comment by maxbec** [comment]
Ok thank you very much! It is working now.
