### ISSUE TITLE
hassio update 1.0 --> 1.2

### ISSUE THREAD

**Issue by seemaexle** [BiasF/Homegear4Homeassistant#2]
Can't execute the update of the addon from1.0 to 1.2. If I hit the button it appears shortly in red and then return to original appearance

21-02-16 12:24:27 INFO (SyncWorker_0) [supervisor.docker.interface] Updating image ae73bafd/armv7-addon-homegear4homeassistant:1.0 to ae73bafd/armv7-addon-homegear4homeassistant:1.2
21-02-16 12:24:27 ERROR (SyncWorker_0) [supervisor.docker.addon] Invalid build envoirement, can't build this add-on!

Running hassio on rp 3b, latest versions (supervisor-2021.02.9 + Home Assistant OS 5.11)

**Comment by Baggerfahrer** [comment]
exactly the same issue here,....

running on a rpi 4b 8gb with  Home Assistant OS 5.12 and supervisor-2021.03.4

**Comment by BiasF** [comment]
Sorry for the late answer.
The update should work now again.
