### ISSUE TITLE
Repository does not work

### ISSUE THREAD

**Issue by stertzi2012** [BiasF/Homegear4Homeassistant#3]
After I added the repository in Hassio it was added.

Here is the log message:

11-17 11:31:44 ERROR (MainThread) [supervisor.store] Can't load data from repository https://github.com/BiasF/homegear4homeassistant/tree/main/homegear4homeassistant
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of testing
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of homegear4homeassistant
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of homegear4homeassistant
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of volkszaehler
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of vzlogger
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of vzlogger
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of homegeartest2
21-11-17 11:31:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of homegeartest2

is there any way to fix this?

**Comment by BiasF** [comment]
Hi,

mhh can't reproduce your issue, but you can ignore the deprecated messages.
Are you able to install the plugin?

You should see the repository in you Supervisor Addon Store:
![image](https://user-images.githubusercontent.com/5191818/142213298-a39fa02d-8b20-4fc1-b619-74e5d45ac3e6.png)

**Comment by stertzi2012** [comment]
Sorry, it works.
Please cole teh issue.

Greeteings
